### ISSUE TITLE
Bu yerda  p ning widhti berilmagan ekan. Yana ijtimoiy tarmoq ikonkalari ham border juda yaqin joylashib qolgan. Shu muammolarni bartaraf etsak yaxshi bo'lardi

### ISSUE THREAD

**Issue by mashhurbek2005** [Bunyood/Namanganliklar#3]
![image](https://user-images.githubusercontent.com/105698306/170074233-8d1840d4-5e8f-4121-95cb-18fc7b707eb8.png)

**Comment by Bunyod1202** [comment]
oka rahmat hamasin togirladm 👌👍

**Comment by Bunyod1202** [comment]
yana kutib qolaman oldindan rahmat
